- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import vpc variables
      include_vars: vars/vpc_setup

    - name: Create Vprofile vpc
      ec2_vpc_net:
       name: "{{vpc_name}}"
       cidr_block: "{{vpcCidr}}"
       region: "{{region}}"
       dns_hostnames: yes
       dns_support: yes
       tenancy: default
       state: "{{state}}"
      register: vpcout
    - debug:
       var: vpcout

    - name: create Public subnet 1 in zone 1
      ec2_vpc_subnet:
       vpc_id: "{{vpcout.vpc.id}}"
       region: "{{region}}"
       az: "{{zone1}}"
       state: "{{state}}"
       cidr: "{{PubSub1Cidr}}"
       map_public: yes
       resource_tags:
        name: vprofile_PubSub1
      register: pubsub1_out

    - name: create Public Subnet 2 in Zone 2
      ec2_vpc_subnet:
       vpc_id: "{{vpcout.vpc.id}}"
       region: "{{region}}"
       az: "{{zone2}}"
       state: "{{state}}"
       cidr: "{{PubSub2Cidr}}"
       map_public: yes
       resource_tags:
        name: vprofile_PubSub2
      register: pubsub2_out

    - name: create Public Subnet 3 in Zone 3
      ec2_vpc_subnet:
       vpc_id: "{{vpcout.vpc.id}}"
       region: "{{region}}"
       az: "{{zone3}}"
       state: "{{state}}"
       cidr: "{{PubSub3Cidr}}"
       map_public: yes
       resource_tags:
        name: vprofile_PubSub3
      register: pubsub3_out